version: '3.8'

services: 
  postgres:
      image: postgres:15
      container_name: meu_postgres
      restart: always
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: senha123
        POSTGRES_DB: labdb
      ports: 
      - "5432:5432"
      volumes: 
      - ./data:/var/lib/postgresql/data
